### ISSUE TITLE
Panic: something went very wrong with peer handling

### ISSUE THREAD

**Issue by ageis** [coyim/coyim#486]
```

  basicGetConversationView(peer=ageis@jabber.calyxinstitute.org/7d5be10a-13c8-4d4e-91d6-a67569ba2d42) with=ageis@jabber.calyxinstitute.org/7d5be10a-13c8-4d4e-91d6-a67569ba2d42 without=ageis@jabber.calyxinstitute.org
    basicGetConversationView(peer=ebfull@jabber.calyxinstitute.org/33fc7389-b63c-4b73-8628-7fe624652885) with=ebfull@jabber.calyxinstitute.org/33fc7389-b63c-4b73-8628-7fe624652885 without=ebfull@jabber.calyxinstitute.org
    basicGetConversationView(peer=elimisteve@jabber.calyxinstitute.org/5550010f-257d-497f-966d-1ddd933b2923) with=elimisteve@jabber.calyxinstitute.org/5550010f-257d-497f-966d-1ddd933b2923 without=elimisteve@jabber.calyxinstitute.org
    basicGetConversationView(peer=elimisteve@jabber.calyxinstitute.org/5550010f-257d-497f-966d-1ddd933b2923) with=elimisteve@jabber.calyxinstitute.org/5550010f-257d-497f-966d-1ddd933b2923 without=elimisteve@jabber.calyxinstitute.org
panic: something went very wrong with peer handling...

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*conversationPane).peerToSendTo(0xc420444000, 0x19584a0, 0xc420088230)
	/home/kevin/go/src/github.com/coyim/coyim/gui/conversation.go:310 +0x145
github.com/coyim/coyim/gui.(*conversationPane).getConversation(0xc420444000, 0xc4201b4f50, 0xcd6d60, 0x0)
	/home/kevin/go/src/github.com/coyim/coyim/gui/conversation.go:367 +0x5e
github.com/coyim/coyim/gui.(*conversationPane).updateSecurityWarning(0xc420444000)
	/home/kevin/go/src/github.com/coyim/coyim/gui/conversation.go:424 +0x2f
github.com/coyim/coyim/gui.(*conversationStackItem).show(0xc4201b3020, 0x0)
	/home/kevin/go/src/github.com/coyim/coyim/gui/unified.go:236 +0x44
github.com/coyim/coyim/gui.(*conversationViewFactory).OpenConversationView(0xc4201b2240, 0xc4201b2200, 0x13, 0xc4201940c0)
	/home/kevin/go/src/github.com/coyim/coyim/gui/conversation_view_owner.go:42 +0x62
github.com/coyim/coyim/gui.(*gtkUI).openConversationView(0xc4201be240, 0xc4201940c0, 0x195d300, 0xc4203a6420, 0xc420083e00, 0x0, 0x0)
	/home/kevin/go/src/github.com/coyim/coyim/gui/ui.go:831 +0xaf
github.com/coyim/coyim/gui.(*gtkUI).handleNotificationEvent(0xc4201be240, 0x1964980, 0xc420226000, 0x195d300, 0xc4203a6420, 0xe13313, 0xa0)
	/home/kevin/go/src/github.com/coyim/coyim/gui/account_events.go:220 +0x7b
github.com/coyim/coyim/gui.(*gtkUI).handleOneAccountEvent.func3()
	/home/kevin/go/src/github.com/coyim/coyim/gui/account_events.go:25 +0x46
reflect.Value.call(0xc7a0c0, 0xc43028cc00, 0x13, 0xdefa54, 0x4, 0x19bc408, 0x0, 0x0, 0xda1680, 0x1, ...)
	/usr/lib/go-1.9/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc7a0c0, 0xc43028cc00, 0x13, 0x19bc408, 0x0, 0x0, 0x0, 0x0, 0xc4200f68e0)
	/usr/lib/go-1.9/src/reflect/value.go:302 +0xa4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.sourceAttach.func2()
	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:311 +0x1be
reflect.Value.call(0xc7a0c0, 0xc4201ca1e0, 0x13, 0xdefa54, 0x4, 0x19bc408, 0x0, 0x0, 0xda1680, 0x38428101, ...)
	/usr/lib/go-1.9/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc7a0c0, 0xc4201ca1e0, 0x13, 0x19bc408, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/reflect/value.go:302 +0xa4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x7f55680017e0, 0x7ffeef285c90, 0xc400000000, 0x0, 0x0, 0x0)
	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x5af
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_d4481ba4042c_goMarshal(0x7f55680017e0, 0x7ffeef285c90, 0x7ffe00000000, 0x0, 0x0, 0x0)
	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:3741 +0x5b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x1ead2f0, 0x0, 0x1f3fae0, 0x0)
	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:900 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x1ead2f0, 0x0, 0x1f3fae0, 0x46af38)
	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0xab
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc4201ae018, 0x19bc408, 0x0, 0x0, 0x0)
	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0x134
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc4201be240)
	/home/kevin/go/src/github.com/coyim/coyim/gui/ui.go:411 +0xe9
main.runClient()
	/home/kevin/go/src/github.com/coyim/coyim/gtk.go:28 +0x1d1
main.main()
	/home/kevin/go/src/github.com/coyim/coyim/main.go:47 +0x63
```
Me and @elimisteve on the same server. I believe he uses libpurple

**Comment by ageis** [comment]
Hey @olabini I have another panic/crash here Sorry the newlines are garbled... Maybe something wrong with my gtk libs?

Btw, there is a bug I experienced while running under CLI. Could not get OTR to work. /otr-start would start a session, but there was some hexadecimal identifier appended to my contact's address which meant it was not verified (precipitating a warning). We appeared to have an active OTR session on both ends, but every time I sent a message it would say the session was not established, so the UI was lying to me or something. Sorry I don't have any output for that.

```
 panic: unknown roster row type: group

                                goroutine 1 [running, locked to thread]:
                                                                        github.com/coyim/coyim/gui.(*roster).onActivateRosterRow(0xc4200780c0, 0x1965d80, 0xc420233440, 0xce5840, 0xc4201f80b8)
                                                                          	/home/kevin/go/src/github.com/coyim/coyim/gui/roster.go:387 +0x42b
                             github.com/coyim/coyim/gui.(*roster).(github.com/coyim/coyim/gui.onActivateRosterRow)-fm(0x1965d80, 0xc420233440, 0xce5840, 0xc4201f80b8)
                                                 	/home/kevin/go/src/github.com/coyim/coyim/gui/roster.go:56 +0x52
   reflect.Value.call(0xca0760, 0xc4200102e0, 0x13, 0xdefdf4, 0x4, 0xc4202b8690, 0x2, 0x2, 0x4, 0xc4201ba000, ...)
                                                                                                                  	/usr/lib/go-1.9/src/reflect/value.go:434 +0x905
                                              reflect.Value.Call(0xca0760, 0xc4200102e0, 0x13, 0xc4202b8690, 0x2, 0x2, 0x2, 0x2, 0xc4201f3500)
                         	/usr/lib/go-1.9/src/reflect/value.go:302 +0xa4
                                                                              github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gliba.FixupFunction.func4(0xde5100, 0xc4201f80a0, 0xce61a0, 0xc4201f80a8)
                                                                                              	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gliba/object.go:117 +0x113
                                                                                    reflect.Value.call(0xca2f20, 0xc42000c1a0, 0x13, 0xdefdf4, 0x4, 0xc4202b85d0, 0x2, 0x2, 0xc4201f80a8, 0xce61a0, ...)
                                                                                   	/usr/lib/go-1.9/src/reflect/value.go:434 +0x905
                  reflect.Value.Call(0xca2f20, 0xc42000c1a0, 0x13, 0xc4202b85d0, 0x2, 0x2, 0xc4202333a0, 0x94, 0x1)
                                                                                                                   	/usr/lib/go-1.9/src/reflect/value.go:302 +0xa4
                                             github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x1de8910, 0x0, 0xc400000003, 0x7ffcc2601420, 0x7ffcc26013a0, 0x0)
                                                              	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x5af
                                          github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_d4481ba4042c_goMarshal(0x1de8910, 0x0, 0x3, 0x7ffcc2601420, 0x7ffcc26013a0, 0x0)
                                                                           	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:3741 +0x5b
                                                    github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x1b81340, 0x0, 0x1cad220, 0x0)
                                                 	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:900 +0x4d
                           github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x1b81340, 0x0, 0x1cad220, 0x46af38)
                             	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0xab
                github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc42000e018, 0x19bc408, 0x0, 0x0, 0x0)
               	/home/kevin/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0x134
 github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc4201e2000)
                                                       	/home/kevin/go/src/github.com/coyim/coyim/gui/ui.go:411 +0xe9
                                                                                                                    main.runClient()
               	/home/kevin/go/src/github.com/coyim/coyim/gtk.go:28 +0x1d1
                                                                          main.main()
                                                                                     	/home/kevin/go/src/github.com/coyim/coyim/main.go:47 +0x63

```
