### ISSUE TITLE
Race conditions in tests

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#544]
There are several race conditions in the tests. We should fix these - they can be seen in Travis among other places, or running the tests several times locally

Issues known that need to be fixed:
- [x] `TestConnClose_sendsAStreamCloseTagWhenWeCloseFirst`
- [x] `SessionSuite.Test_WatchStanzas_presence_ignoresSameState`
- [x] `SessionSuite.Test_WatchStanzas_getsUnknown`

**Comment by olabiniV2** [comment]
One seems to hang forever sometimes, like this one: https://travis-ci.org/github/coyim/coyim/jobs/674813106
```

goroutine 200 [chan receive]:
github.com/coyim/coyim/xmpp.(*XMPPSuite).TestConnClose_sendsAStreamCloseTagWhenWeCloseFirst(0xb7c4f8, 0xc42039fc20)
	/home/travis/gopath/src/github.com/coyim/coyim/xmpp/xmpp_test.go:125 +0x534
reflect.Value.call(0x89fc60, 0xb7c4f8, 0xa13, 0x8c4972, 0x4, 0xc420061f70, 0x1, 0x1, 0xb7de00, 0x8bb8c0, ...)
	/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x89fc60, 0xb7c4f8, 0xa13, 0xc4201f6770, 0x1, 0x1, 0x0, 0xc4201f6707, 0x1)
	/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc42039fc20)
	/home/travis/gopath/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:772 +0x575
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc42013f200, 0xc42039fc20, 0xc4203c5d80)
	/home/travis/gopath/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:666 +0x7c
created by github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/home/travis/gopath/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:663 +0x20c
```

**Comment by olabiniV2** [comment]
This one I've seen locally sometimes: https://travis-ci.org/github/coyim/coyim/jobs/689703595
```
----------------------------------------------------------------------
FAIL: session_test.go:775: SessionSuite.Test_WatchStanzas_presence_ignoresSameState

session_test.go:805:
    c.Error("Received presence event")
... Error: Received presence event

OOPS: 36 passed, 1 FAILED
--- FAIL: Test (1.02s)
```

**Comment by olabiniV2** [comment]
Another one in the xmpp package: https://travis-ci.org/github/coyim/coyim/jobs/541191129
```

----------------------------------------------------------------------
FAIL: xmpp_test.go:89: XMPPSuite.TestConnClose_sendsAStreamCloseTagWhenWeCloseFirst

xmpp_test.go:122:
    c.Assert(mockCloser.CalledClose(), Equals, true)
... obtained bool = false
... expected bool = true

OOPS: 137 passed, 1 FAILED
--- FAIL: Test (2.30s)
```

**Comment by olabiniV2** [comment]
I've fixed all the problematic tests, but there are lots of other tests in session_test.go I want to make sure actually does the right thing.

**Comment by olabiniV2** [comment]
In the latest commit I've fixed up the tests, making them more robust against timing and race conditions.
