### ISSUE TITLE
Error when the certificate window is closed on account registration

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#547]
We have the next error messages:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9b8650]

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*gtkUI).certificateFailedToVerifyDisplayDialog.func1()
	/home/sham/go/src/github.com/coyim/coyim/gui/certificate_window.go:160 +0x1200
reflect.Value.call(0xced320, 0xc0003650e0, 0x13, 0xe82c64, 0x4, 0x1a84630, 0x0, 0x0, 0xc0001cf838, 0x4a5f9c, ...)
	/usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xced320, 0xc0003650e0, 0x13, 0x1a84630, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/reflect/value.go:321 +0xb4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x7f78280013f0, 0x7ffde4320e10, 0x0, 0x0, 0x0, 0x0)
	/home/sham/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x583
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_7bd2ed847f3e_goMarshal(0x7f78280013f0, 0x7ffde4320e10, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:4256 +0x5b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x26530f0, 0x0, 0x243bc50, 0x0)
	_cgo_gotypes.go:1224 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc000194030, 0x1a84630, 0x0, 0x0, 0x243bc50, 0xe86951)
	/home/sham/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0xa6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc000194030, 0x1a84630, 0x0, 0x0, 0x0)
	/home/sham/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x181
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc000196000)
	/home/sham/go/src/github.com/coyim/coyim/gui/ui.go:411 +0xca
main.runClient()
	/home/sham/go/src/github.com/coyim/coyim/main.go:77 +0x1cb
main.main()
	/home/sham/go/src/github.com/coyim/coyim/main.go:62 +0xff

```

**Comment by olabiniV2** [comment]
This is very likely because an action is happening outside the UI thread.
