### ISSUE TITLE
CoyIM crashes when adding a contact

### ISSUE THREAD

**Issue by rafaelbonifaz** [coyim/coyim#714]
The error occurs when you want to add a contact. After you finish adding the contact CoyIM crashes. The other side would receive the invitation.

This the output of the error:

```
time="2021-03-09T09:52:44-05:00" level=info msg="Roster received" account=sandytest1@testjabber.autonomia.digital component=session

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x88 pc=0x7ff60c71ee64]

goroutine 1 [running, locked to thread]:

github.com/coyim/coyim/gui.(\*errorNotification).Hide(0xc000336140)

        C:/Users/cad/go/src/github.com/coyim/coyim/gui/error_notification.go:42 +0x44

github.com/coyim/coyim/gui.(\*addContactDialog).clearErrors(0xc0002b2200)

        C:/Users/cad/go/src/github.com/coyim/coyim/gui/subscription.go:42 +0x36

github.com/coyim/coyim/gui.(\*connectedAccountsComponent).initOrReplaceAccounts(0xc0000d80e0, 0xc0000ca6e0, 0x1, 0x1)

        C:/Users/cad/go/src/github.com/coyim/coyim/gui/connected*accounts*component.go:109 +0x33a

github.com/coyim/coyim/gui.(\*gtkUI).createConnectedAccountsComponent.func2.1()

        C:/Users/cad/go/src/github.com/coyim/coyim/gui/connected*accounts*component.go:152 +0x4f

reflect.Value.call(0x7ff60cd7e1c0, 0xc000336660, 0x13, 0x7ff60cf4ffed, 0x4, 0x7ff60dfb3898, 0x0, 0x0, 0xc0005a3880, 0x7ff60c1bdb03, ...)

        C:/Program Files/Go/src/reflect/value.go:460 +0x8b2

reflect.Value.Call(0x7ff60cd7e1c0, 0xc000336660, 0x13, 0x7ff60dfb3898, 0x0, 0x0, 0x0, 0x0, 0x0)

        C:/Program Files/Go/src/reflect/value.go:321 +0xbb

github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x240ffa57590, 0x57d49ff8f0, 0xc000000000, 0x0, 0x0, 0x0)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:250 +0x70a

github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.*cgoexpwrap*3ce6c0691c80_goMarshal(0x240ffa57590, 0x57d49ff8f0, 0x0, 0x0, 0x0, 0x0)

        *cgo*gotypes.go:4460 +0x62

github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.*Cfunc*g*application*run(0x240ff8070f0, 0x24000000000, 0x240d99622c0, 0x0)

        *cgo*gotypes.go:1242 +0x54

github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(\*Application).Run.func4(0xc00022aff0, 0x7ff60dfb3898, 0x0, 0x0, 0x240d99622c0, 0x7ff60c7d46b4)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x9b

github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(\*Application).Run(0xc00022aff0, 0x7ff60dfb3898, 0x0, 0x0, 0x0)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x18e

github.com/coyim/coyim/gui.(\*gtkUI).Loop(0xc00009cf00)

        C:/Users/cad/go/src/github.com/coyim/coyim/gui/ui.go:419 +0xd4

main.runClient()

        C:/Users/cad/go/src/github.com/coyim/coyim/main.go:95 +0x1f3

main.main()

        C:/Users/cad/go/src/github.com/coyim/coyim/main.go:80 +0xd5
```

**Comment by olabiniV2** [comment]
Have you verified whether this functionality works in Linux with the latest version of Coy?

**Comment by olabiniV2** [comment]
I can't replicate this all the time. I also got a similar looking stack trace when doing something slightly different:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0xa49e65]

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*errorNotification).ShowMessage(0xc000014a20, 0xc0003a2870, 0x29)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/error_notification.go:37 +0x315
github.com/coyim/coyim/gui.(*addContactDialog).notifyOnError(0xc000248300, 0xc0003a2870, 0x29)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/subscription.go:50 +0x54
github.com/coyim/coyim/gui.(*gtkUI).presenceSubscriptionDialog.func2.1()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/subscription.go:102 +0x75
reflect.Value.call(0xe85b20, 0xc00024fec0, 0x13, 0x1066cc9, 0x4, 0x234cc20, 0x0, 0x0, 0xc0000e9950, 0x4bc1cc, ...)
	/home/amnesia/Persistent/src/go-1.14.3/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0xe85b20, 0xc00024fec0, 0x13, 0x234cc20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/amnesia/Persistent/src/go-1.14.3/src/reflect/value.go:321 +0xb4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x7922c8001720, 0x7ffc0c876ae0, 0xc000000000, 0x0, 0x0, 0x0)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:250 +0x703
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_3ce6c0691c80_goMarshal(0x7922c8001720, 0x7ffc0c876ae0, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:4454 +0x5b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x3304280, 0x0, 0x33a17b0, 0x0)
	_cgo_gotypes.go:1236 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc00007e5d0, 0x234cc20, 0x0, 0x0, 0x33a17b0, 0xb0075d)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x94
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc00007e5d0, 0x234cc20, 0x0, 0x0, 0x0)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x187
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc000332000)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/ui.go:419 +0xcd
main.runClient()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/main.go:123 +0x192
main.main()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/main.go:100 +0xc5
```
