### ISSUE TITLE
CoyIM crashes in Windows when starting a secure chat

### ISSUE THREAD

**Issue by rafaelbonifaz** [coyim/coyim#715]
When you want to start a secure chat in the latest version of Coy for Windows (at the moment), it would crash.

This is the output:

```
goroutine 47 [running]:

github.com/coyim/coyim/vendor/github.com/awnumar/memcall.Unlock(0x0, 0x0, 0x0, 0x7ff60c263f13, 0xc00055ba21)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/awnumar/memcall/memcall_windows.go:28 +0x124

github.com/coyim/coyim/vendor/github.com/coyim/otr3.tryUnlock(...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/memory_lock.go:24

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*ake).wipe(0xc000324000, 0x7ff60c17e401)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/wipe.go:41 +0x68

github.com/coyim/coyim/vendor/github.com/coyim/otr3.authStateNone.receiveDHCommitMessage(0xc0000cca00, 0xc00008490b, 0xec, 0xee, 0xc0001fb398, 0xc0001fb360, 0x7ff60c17ed0f, 0x1c0, 0x7ff60ce81880, 0x7ff60c1a7401, ...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/auth*state*machine.go:83 +0x42

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).processAKE(0xc0000cca00, 0x2, 0xc00008490b, 0xec, 0xee, 0xf9, 0xc00008490b, 0xec, 0xee, 0x0)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/auth*state*machine.go:38 +0x485

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).receiveAKEMessage(0xc0000cca00, 0xc0000cca02, 0xc00008490b, 0xec, 0xee, 0xc000084900, 0xb, 0xf9, 0xc00008490b, 0xec, ...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/receive.go:163 +0x63

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).receiveDecoded(0xc0000cca00, 0xc000084900, 0xf7, 0xf9, 0xf7, 0xf9, 0x0, 0x0, 0x160, 0x52544f3f00000029, ...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/receive.go:158 +0x27e

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).receiveEncoded(0xc0000cca00, 0xc0000d29a0, 0x152, 0x160, 0x152, 0xc0000d29a0, 0x0, 0x160, 0x3, 0xc0000b4fc0, ...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/receive.go:99 +0xd0

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).receiveUnit(0xc0000cca00, 0xc0000d2840, 0x152, 0x160, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/receive.go:40 +0x688

github.com/coyim/coyim/vendor/github.com/coyim/otr3.(\*Conversation).Receive(...)

        C:/Users/cad/go/src/github.com/coyim/coyim/vendor/github.com/coyim/otr3/receive.go:5

github.com/coyim/coyim/otrclient.(\*conversation).Receive(0xc000134000, 0xc0000d2840, 0x152, 0x160, 0x152, 0x160, 0x7ff60d3d73e0, 0xc000134000, 0x0)

        C:/Users/cad/go/src/github.com/coyim/coyim/otrclient/conversation.go:103 +0x77

github.com/coyim/coyim/session.(\*session).receiveClientMessage(0xc000298680, 0x7ff60d3d48e0, 0xc0002234a0, 0xc00a0114de2c1280, 0xd5a958ba5, 0x7ff60df82e40, 0xc0000d26e0, 0x152)

        C:/Users/cad/go/src/github.com/coyim/coyim/session/session.go:518 +0xfd

github.com/coyim/coyim/session.(\*session).receivedClientMessage(0xc000298680, 0xc00053a180, 0x1)

        C:/Users/cad/go/src/github.com/coyim/coyim/session/session.go:258 +0x53f

github.com/coyim/coyim/session.(\*session).receiveStanza(0xc000298680, 0xc000533080, 0xc000298601)

        C:/Users/cad/go/src/github.com/coyim/coyim/session/session.go:396 +0x2eb

github.com/coyim/coyim/session.(\*session).watchStanzas(0xc000298680)

        C:/Users/cad/go/src/github.com/coyim/coyim/session/session.go:418 +0xb2

created by github.com/coyim/coyim/session.(\*session).Connect

        C:/Users/cad/go/src/github.com/coyim/coyim/session/session.go:855 +0x508
```

**Comment by sacurio** [comment]
Just one test failed for OTRv3:

```
go test -cover -v ./...
[...]
--- FAIL: Test_receiveDHCommit_TransitionsFromNoneToAwaitingRevealSigAndSendDHKeyMsg (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 53 [running]:
testing.tRunner.func1.1(0x67e8e0, 0xc00000cba0)
	C:/Program Files/Go/src/testing/testing.go:999 +0x320
testing.tRunner.func1(0xc00012d0e0)
	C:/Program Files/Go/src/testing/testing.go:1002 +0x409
panic(0x67e8e0, 0xc00000cba0)
	C:/Program Files/Go/src/runtime/panic.go:969 +0x174
github.com/coyim/otr3/vendor/github.com/awnumar/memcall.Unlock(0x0, 0x0, 0x0, 0xf7, 0xc000000500)
	C:/Users/cad/go/src/github.com/coyim/otr3/vendor/github.com/awnumar/memcall/memcall_windows.go:28 +0x124
github.com/coyim/otr3.tryUnlock(...)
	C:/Users/cad/go/src/github.com/coyim/otr3/memory_lock.go:24
github.com/coyim/otr3.(*ake).wipe(0xc000260000, 0xc000000501)
	C:/Users/cad/go/src/github.com/coyim/otr3/wipe.go:41 +0x75
github.com/coyim/otr3.authStateNone.receiveDHCommitMessage(0xc0000bef00, 0xc00000050b, 0xec, 0xf5, 0x4db610, 0x7bf8d8, 0x88b0a0, 0x4dfa00, 0x1, 0xc00000b010, ...)
	C:/Users/cad/go/src/github.com/coyim/otr3/auth_state_machine.go:83 +0x4c
github.com/coyim/otr3.Test_receiveDHCommit_TransitionsFromNoneToAwaitingRevealSigAndSendDHKeyMsg(0xc00012d0e0)
	C:/Users/cad/go/src/github.com/coyim/otr3/auth_state_machine_test.go:15 +0x20c
testing.tRunner(0xc00012d0e0, 0x6bbc78)
	C:/Program Files/Go/src/testing/testing.go:1050 +0xe3
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1095 +0x292
FAIL	github.com/coyim/otr3	0.505s
[...]
coverage: 100.0% of statements
ok  	github.com/coyim/otr3/sexp	(cached)	coverage: 100.0% of statements
FAIL
```

**Comment by olabiniV2** [comment]
Sandy has identified the problem that causes this issue. I created a fork at https://github.com/olabiniV2/memcall and sent in a pull request to the original project here: https://github.com/awnumar/memcall/pull/7 - if the original developer accepts the pull request, we will simply update the dependency in OTR3 and then update OTR3 inside of CoyIM. Otherwise we will change to use the fork instead.

**Comment by olabiniV2** [comment]
This has been fixed with the merging of the memcall fix, updated in OTR3 and merged with CoyIM.
