### ISSUE TITLE
CoyIM crashes when adding a new contact.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#825]
Error log:
```
panic: Unrecognized type of object: <nil>

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gtka.Wrap(0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gtka/wrap_map.go:20 +0xe1
github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gtka.(*widget).GetParent(0xc0002a44b0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gtka/widget.go:114 +0x68
github.com/coyim/coyim/gui.(*errorNotification).Hide(0xc000429040)
	/gopath/src/github.com/coyim/coyim/gui/error_notification.go:43 +0x33
github.com/coyim/coyim/gui.(*addContactDialog).clearErrors(0xc000244d80)
	/gopath/src/github.com/coyim/coyim/gui/subscription.go:42 +0x2f
github.com/coyim/coyim/gui.(*connectedAccountsComponent).initOrReplaceAccounts(0xc000256070, 0xc010a10240, 0x2, 0x7)
	/gopath/src/github.com/coyim/coyim/gui/connected_accounts_component.go:109 +0x333
github.com/coyim/coyim/gui.(*gtkUI).createConnectedAccountsComponent.func2.1()
	/gopath/src/github.com/coyim/coyim/gui/connected_accounts_component.go:152 +0x47
reflect.Value.call(0x1016240, 0xc010a141e0, 0x13, 0x1230f31, 0x4, 0x0, 0x0, 0x0, 0xc000555950, 0x931652, ...)
	/root/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1016240, 0xc010a141e0, 0x13, 0x0, 0x0, 0x0, 0x16033d8, 0x0, 0xc000555a08)
	/root/go/src/reflect/value.go:321 +0xb4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.sourceFunc(0x4, 0x1603390)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:324 +0xe6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_5c31e9bacecb_sourceFunc(0x4, 0x7fc656e2e730)
	_cgo_gotypes.go:6312 +0x2b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x3d1d0f0, 0x0, 0x3a913e0, 0x0)
	_cgo_gotypes.go:1531 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc000508360, 0x29afb38, 0x0, 0x0, 0x3a913e0, 0x13)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0xa6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc000508360, 0x29afb38, 0x0, 0x0, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0x181
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc000470000)
	/gopath/src/github.com/coyim/coyim/gui/ui.go:405 +0xc8
main.runClient()
	/gopath/src/github.com/coyim/coyim/main.go:161 +0x188
main.main()
	/gopath/src/github.com/coyim/coyim/main.go:134 +0x190
```

**Comment by azlancpool** [comment]
It's ready to `user-test`

**Comment by azlancpool** [comment]
The issue was closed by error

**Comment by olabiniV2** [comment]
OK
