### ISSUE TITLE
CoyIM crashes when losts connection with a server

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#827]
The log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xd1537c]

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*account).Account(...)
	/gopath/src/github.com/coyim/coyim/gui/account.go:112
github.com/coyim/coyim/gui.(*mucPublicRoomsView).onAccountsUpdated(0xc0003f77a0, 0x0)
	/gopath/src/github.com/coyim/coyim/gui/muc_public_rooms.go:161 +0x8c
github.com/coyim/coyim/gui.(*connectedAccountsComponent).initOrReplaceAccounts(0xc010496070, 0xc000443c00, 0x1, 0x7)
	/gopath/src/github.com/coyim/coyim/gui/connected_accounts_component.go:110 +0x36b
github.com/coyim/coyim/gui.(*gtkUI).createConnectedAccountsComponent.func2.1()
	/gopath/src/github.com/coyim/coyim/gui/connected_accounts_component.go:152 +0x47
reflect.Value.call(0x1016240, 0xc0004a8be0, 0x13, 0x1230f31, 0x4, 0x0, 0x0, 0x0, 0xc00015f950, 0x931652, ...)
	/root/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1016240, 0xc0004a8be0, 0x13, 0x0, 0x0, 0x0, 0x16033d8, 0x0, 0xc00015fa08)
	/root/go/src/reflect/value.go:321 +0xb4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.sourceFunc(0x7, 0x1603390)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:324 +0xe6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_5c31e9bacecb_sourceFunc(0x7, 0x7f83be412730)
	_cgo_gotypes.go:6312 +0x2b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x44fb0f0, 0x0, 0x42684d0, 0x0)
	_cgo_gotypes.go:1531 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc000274720, 0x29afb38, 0x0, 0x0, 0x42684d0, 0x13)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0xa6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc000274720, 0x29afb38, 0x0, 0x0, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0x181
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc000278000)
	/gopath/src/github.com/coyim/coyim/gui/ui.go:405 +0xc8
main.runClient()
	/gopath/src/github.com/coyim/coyim/main.go:161 +0x188
main.main()
	/gopath/src/github.com/coyim/coyim/main.go:134 +0x190
```

**Comment by azlancpool** [comment]
It's ready to `code-review`

**Comment by olabiniV2** [comment]
Looks good.
