### ISSUE TITLE
Crash in getting public rooms

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#829]
This crash happened long after I shut down the dialog for public rooms. It seems that maybe it stays in memory and then fails at some point: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xcf3f8c]

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*account).Account(...)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/account.go:112
github.com/coyim/coyim/gui.(*mucPublicRoomsView).onAccountsUpdated(0xc0001e6240, 0x0)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/muc_public_rooms.go:161 +0x8c
github.com/coyim/coyim/gui.(*connectedAccountsComponent).initOrReplaceAccounts(0xc0105ac000, 0xc011bfd8c0, 0x5, 0x7)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/connected_accounts_component.go:110 +0x36b
github.com/coyim/coyim/gui.(*gtkUI).createConnectedAccountsComponent.func2.1()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/connected_accounts_component.go:152 +0x47
reflect.Value.call(0xfd47e0, 0xc010b48200, 0x13, 0x11de9b2, 0x4, 0x0, 0x0, 0x0, 0x284f7c0, 0x0, ...)
	/home/amnesia/Persistent/src/go-1.14.3/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0xfd47e0, 0xc010b48200, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/amnesia/Persistent/src/go-1.14.3/src/reflect/value.go:321 +0xb4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.sourceFunc(0x1a, 0x8)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:324 +0xe6
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_66f2ca9a726e_sourceFunc(0x1a, 0x7e995c0032f0)
	_cgo_gotypes.go:6313 +0x2b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x37fb280, 0x0, 0x38fa510, 0x0)
	_cgo_gotypes.go:1532 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc0002a5d70, 0x284f5c8, 0x0, 0x0, 0x38fa510, 0xfd47e0)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0x94
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc0002a5d70, 0x284f5c8, 0x0, 0x0, 0x0)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0x187
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc0000ac280)
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/gui/ui.go:405 +0xc8
main.runClient()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/main.go:161 +0x188
main.main()
	/home/amnesia/Persistent/.gopaths/coyim/src/github.com/coyim/coyim/main.go:134 +0x178
```

**Comment by azlancpool** [comment]
It's ready to `code-review`

**Comment by olabiniV2** [comment]
Looks good.
